INSERT INTO recipes (title, description, ingredients, cuisine, cooking_time) VALUES
    ('Spaghetti Carbonara', 'A classic Italian pasta dish with eggs, cheese, pancetta, and black pepper.', 'spaghetti, eggs, Pecorino Romano, Parmigiano-Reggiano, pancetta, black pepper', 'Italian', 25),
    ('Chicken Tikka Masala', 'Tender chicken in a spicy tomato-based sauce.', 'chicken breast, yogurt, lemon juice, garam masala, ginger, garlic, tomato puree, heavy cream', 'Indian', 45),
    ('Sushi Rolls', 'Fresh sushi rolls with avocado and cucumber.', 'sushi rice, nori sheets, avocado, cucumber, soy sauce, wasabi', 'Japanese', 30),
    ('Beef Stroganoff', 'Hearty beef dish served with egg noodles.', 'beef sirloin, onions, mushrooms, beef broth, sour cream, egg noodles', 'Russian', 50),
    ('Pad Thai', 'Stir-fried rice noodles with shrimp, chicken, or tofu.', 'rice noodles, shrimp, chicken, tofu, eggs, bean sprouts, garlic chives, crushed peanuts, lime wedges', 'Thai', 30),
    ('Paella', 'A Spanish dish with saffron-infused rice, seafood, and vegetables.', 'bomba rice, saffron, chicken, shrimp, mussels, bell peppers, peas, olive oil', 'Spanish', 60),
    ('Chicken Fajitas', 'Sizzling chicken with peppers and onions, served with tortillas.', 'chicken breast, bell peppers, onions, tortillas, lime, cilantro, avocado', 'Mexican', 30),
    ('Lasagna', 'Layers of pasta, meat sauce, and cheese.', 'lasagna noodles, ground beef, ricotta cheese, mozzarella cheese, tomato sauce, onions, garlic', 'Italian', 60),
    ('Chicken Shawarma', 'Marinated chicken slices served with pita bread.', 'chicken breast, yogurt, lemon juice, garlic, shawarma spices, pita bread, tahini sauce', 'Middle Eastern', 45),
    ('Vegetable Stir Fry', 'A medley of vegetables stir-fried with soy sauce.', 'mixed vegetables, soy sauce, garlic, ginger, sesame oil, rice', 'Chinese', 20),
    ('Fish and Chips', 'Crispy fried fish with a side of chips.', 'cod fillets, potatoes, beer batter, tartar sauce, lemon wedges', 'British', 30),
    ('Chicken Curry', 'A flavorful chicken curry with coconut milk.', 'chicken breast, coconut milk, curry powder, onions, garlic, ginger, tomatoes', 'Indian', 40),
    ('Pizza Margherita', 'A classic pizza with tomatoes, mozzarella, and basil.', 'pizza dough, tomatoes, mozzarella cheese, fresh basil, olive oil', 'Italian', 20),
    ('Beef Tacos', 'Ground beef tacos with lettuce, tomatoes, and cheese.', 'ground beef, taco shells, lettuce, tomatoes, cheddar cheese, taco seasoning', 'Mexican', 20),
    ('Shrimp Scampi', 'Shrimp cooked in a garlic butter sauce.', 'shrimp, butter, garlic, white wine, lemon juice, red pepper flakes, parsley', 'Italian', 20),
    ('Chicken Biryani', 'Aromatic rice dish with chicken and spices.', 'chicken breast, basmati rice, yogurt, biryani spices, onions, tomatoes, ginger, garlic', 'Indian', 60),
    ('Greek Salad', 'A refreshing salad with tomatoes, cucumbers, and feta cheese.', 'tomatoes, cucumbers, feta cheese, Kalamata olives, red onion, olive oil, vinegar', 'Greek', 15),
    ('Chicken Caesar Salad', 'Grilled chicken with romaine lettuce and Caesar dressing.', 'chicken breast, romaine lettuce, Caesar dressing, croutons, Parmesan cheese', 'American', 20),
    ('Vegetable Soup', 'A hearty soup with a variety of vegetables.', 'mixed vegetables, vegetable broth, onions, garlic, tomatoes, herbs', 'American', 40),
    ('Chicken Quesadilla', 'A cheesy quesadilla filled with chicken and vegetables.', 'chicken breast, tortillas, cheese, bell peppers, onions, salsa, sour cream', 'Mexican', 20),
    ('Eggplant Parmesan', 'Breaded eggplant slices with tomato sauce and cheese.', 'eggplant, breadcrumbs, tomato sauce, mozzarella cheese, Parmesan cheese, eggs', 'Italian', 45),
    ('Chicken Satay', 'Marinated chicken skewers with peanut sauce.', 'chicken breast, soy sauce, peanut butter, coconut milk, garlic, ginger, skewers', 'Thai', 30),
    ('Beef Bourguignon', 'A rich beef stew cooked with red wine.', 'beef chuck, red wine, beef broth, onions, carrots, garlic, bacon, mushrooms', 'French', 120),
    ('Chicken Teriyaki', 'Chicken marinated in a sweet and savory teriyaki sauce.', 'chicken breast, teriyaki sauce, soy sauce, mirin, sake, garlic, ginger', 'Japanese', 30),
    ('Lentil Soup', 'A comforting soup made with lentils and vegetables.', 'lentils, vegetable broth, onions, carrots, celery, garlic, tomatoes, herbs', 'Middle Eastern', 45),
    ('Chicken Cacciatore', 'Chicken stewed with tomatoes, peppers, and herbs.', 'chicken breast, tomatoes, bell peppers, onions, garlic, herbs, white wine', 'Italian', 45),
    ('Vegetable Curry', 'A flavorful curry with a variety of vegetables.', 'mixed vegetables, coconut milk, curry powder, onions, garlic, ginger, tomatoes', 'Indian', 35),
    ('Chicken Parmesan', 'Breaded chicken cutlets with tomato sauce and cheese.', 'chicken breast, breadcrumbs, tomato sauce, mozzarella cheese, Parmesan cheese, eggs', 'Italian', 40),
    ('Stuffed Bell Peppers', 'Bell peppers filled with a mixture of rice, meat, and cheese.', 'bell peppers, ground beef, rice, cheese, tomato sauce, onions, garlic', 'American', 45),
    ('Chicken and Vegetable Stir Fry', 'A quick stir fry with chicken and mixed vegetables.', 'chicken breast, mixed vegetables, soy sauce, garlic, ginger, sesame oil, rice', 'Chinese', 25);
